apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-music 
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-music
spec:
  source:
    git:
      url: https://github.com/dsboulder/spring-music.git
      ref:
        branch: workload
